# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autifyctl < Formula
  desc "CLI tool for Autify API"
  homepage "https://github.com/kutifyhq/autifyctl"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.1/autifyctl_0.0.1_darwin_amd64.tar.gz"
    sha256 "ea33f700c310103c79c7a2e77b573003694169509532daa6af5c18ae82a1ef31"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.1/autifyctl_0.0.1_darwin_arm64.tar.gz"
    sha256 "09b443c91e9b6be9a8c9ff1edcdb8e374e7b97112d94be82ae763a8ebcf9d425"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.1/autifyctl_0.0.1_linux_amd64.tar.gz"
    sha256 "54a320d1c45583395dc254bf32bc9f43ea2f58fe2fbcdaa539c4869bafd42a2d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.1/autifyctl_0.0.1_linux_arm64.tar.gz"
    sha256 "d2d1a60111528de3403dedd2e24a0b4cc5c362054ae888c3256d05ce8350336f"
  end

  def install
    bin.install "autifyctl"
  end

  test do
    system "#{bin}/autifyctl --version"
  end
end
