# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autifyctl < Formula
  desc "CLI tool for Autify API"
  homepage "https://github.com/kutifyhq/autifyctl"
  version "0.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.2/autifyctl_0.0.2_darwin_amd64.tar.gz"
    sha256 "a42c542b88155a084250a0bd4ec8b9c3ba84a8dbcf55295ea5efa65f0b4e40bf"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.2/autifyctl_0.0.2_darwin_arm64.tar.gz"
    sha256 "13e385be8aa67fe8b759b3a94e07462b384eb69f156132944d8a7f6b9e2bd848"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.2/autifyctl_0.0.2_linux_amd64.tar.gz"
    sha256 "259f97dc5a63944e5eee8539e1d77a130a18f44227ca2a1518ae8fdca2e25ccb"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.2/autifyctl_0.0.2_linux_arm64.tar.gz"
    sha256 "8723d626d9ff167d4285a289114aeddb6eafd3d1f1572487b1e650c479bc689f"
  end

  def install
    bin.install "autifyctl"
  end

  test do
    system "#{bin}/autifyctl --version"
  end
end
