# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autifyctl < Formula
  desc "CLI tool for Autify API"
  homepage "https://github.com/kutifyhq/autifyctl"
  version "0.0.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.4/autifyctl_0.0.4_darwin_amd64.tar.gz"
    sha256 "ada4c093a71c43b269fdef295cc84407b4f3300bd9b24e46d0236dd7be293995"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.4/autifyctl_0.0.4_darwin_arm64.tar.gz"
    sha256 "763a56216052eef8d2442da0fd610a1e1ab9e1d1ade80e463a9ad2362e7d0b16"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.4/autifyctl_0.0.4_linux_amd64.tar.gz"
    sha256 "c0ab8bf939d4b327137dfa77dd7cebfce1b4ff5829d54b940cfea2168fcece22"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/kutifyhq/autifyctl/releases/download/v0.0.4/autifyctl_0.0.4_linux_arm64.tar.gz"
    sha256 "fe51ab8a8d13efeff3e8dda443ab0ce7a839b11fbe665067b75b5dd3eafc675f"
  end

  def install
    bin.install "autifyctl"
  end

  test do
    system "#{bin}/autifyctl --version"
  end
end
